
const TOGGLE_DEVICE = 'XXTOGGLE_DEVICEX'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const IS_AUTHENTICATED = 'IS_AUTHENTICATED'

export default {
  TOGGLE_DEVICE,
  TOGGLE_SIDEBAR,
  IS_AUTHENTICATED
}
